### PR TITLE
1.18 support

### PR DESCRIPTION
**Pull request by extremeheat**
* needs https://github.com/PrismarineJS/prismarine-chunk/pull/162
* support prismarine-registry
* reading/writing (kind of) works, but there is a bug with bits per block between 1 and 3. World looks OK in prismarine-viewer with those chunks removed (ignoring the incorrect grass textures re-used from 1.16) : 
image

### CODE REVIEW

**Comment by nickelpro** [comment]
WAIT I KNOW WHAT THE BUG IS

**Comment by extremeheat** [comment]
fixed bits per block issue for 1-3 per nickelpro comment, issue was mojang changes 1-4 bits per block to 4,
```java
@Override
public <A> Configuration<A> getConfiguration(IdMap<A> idMap, int n) {
    Configuration configuration = switch (n) {
        case 0 -> new Configuration(SINGLE_VALUE_PALETTE_FACTORY, n);
        case 1, 2, 3, 4 -> new Configuration(LINEAR_PALETTE_FACTORY, 4);
        case 5, 6, 7, 8 -> new Configuration(HASHMAP_PALETTE_FACTORY, n);
        default -> new Configuration(GLOBAL_PALETTE_FACTORY, Mth.ceillog2(idMap.size()));
    };
    return configuration;
}
```

**Comment by rom1504** [comment]
I'd suggest changing package.json to depend on the branches you need of dependencies so CI can run here

**Comment by rom1504** [comment]
is this ready ?

**Comment by rom1504** [comment]
tests failing

**Comment by extremeheat** [comment]
Fixed, https://github.com/PrismarineJS/prismarine-nbt/pull/61/files implements the NBT wrappers there but it's not that important

**Pull request merged**
