### PR TITLE
1.13 implementation

### PR DESCRIPTION
**Pull request by Karang**

### CODE REVIEW

**Comment by rom1504** [comment]
can you rebase on master so CI will run ?

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/prismarine-provider-anvil/issues/22

**Review by rom1504 — CHANGES_REQUESTED** [review]
Would be great if you could update the tests so they can work with these 2 versions (you can use any region file as test data)

**Comment by Karang** [comment]
> Would be great if you could update the tests so they can work with these 2 versions (you can use any region file as test data)

I adapted the chunkToNbt test, this should be enough to test the new 1.13 implementation. Note that there is no test that read real region data (the .mca in world/lttp is not used in the tests).

**Comment by rom1504** [comment]
Ah you're right, could you also adapt https://github.com/PrismarineJS/prismarine-provider-anvil/blob/master/test/savingLoading.js ?

**Comment by Karang** [comment]
> Ah you're right, could you also adapt https://github.com/PrismarineJS/prismarine-provider-anvil/blob/master/test/savingLoading.js ?

Done. It was useful to catch a few bugs.

**Comment by rom1504** [comment]
Great, thanks !
Let's merge this

**Review by rom1504 — APPROVED** [review]

**Pull request merged**
