### PR TITLE
Fix 1.17 support

### PR DESCRIPTION
**Pull request by Saiv46**
My bad, I haven't checked 1.17 chunk implementation that differs from 1.16, so code cannot be reused much.

### CODE REVIEW

**Comment by rom1504** [comment]
why didn't the tests fail previously?

can you improve tests to catch this?

**Comment by rom1504** [comment]
looks like it's failing now

**Comment by Saiv46** [comment]
> looks like it's failing now

For some reason `getMask()` returns 0 on 1.17

**Comment by Saiv46** [comment]
Blocked by PrismarineJS/prismarine-chunk#144

**Comment by Saiv46** [comment]
Closed wrong PR

**Comment by rom1504** [comment]
should I close this? is there an actual bug?

**Comment by Saiv46** [comment]
Closed because I haven't finished it in reasonable time.

Anyone can use this as base for new PR if needed.

**Comment by rom1504** [comment]
can you say if you observed that 1.17 support was broken ? (in current master)

**Comment by Saiv46** [comment]
I observed that it brokes when flying-squid uses it, so I closed this PR because I was not sure is the issue with this package.

I'm sorry.

**Pull request closed without merging**
