### PR TITLE
Add support for 1.14, 1.15 and 1.16

### LINKED ISSUE #22: add support for 1.14, 1.15 and 1.16
see https://minecraft.gamepedia.com/Talk:Chunk_format#Parsing_Heightmaps_field_.281.15.2.29

### PR DESCRIPTION
**Pull request by IdanHo**
Closes #22 needed for PrismarineJS/flying-squid#430 so a new version should be released once this is merged
Currently doesnt store heightmaps (meaning the vanilla server regenerates them on load), if and once we implement them in prismarine-chunk, this should be updated.

### CODE REVIEW

**Review by rom1504 — CHANGES_REQUESTED** [review]
Looks good, thanks for working on this!
Could you explain in a few words what are the changes you made between 1.13 and 1.14 and 1.16?
Could you try to put some of the functions that are duplicated in a common/ directory to avoid some code duplication?

**Comment by IdanHo** [comment]
Sure:
- 1.13 was already implemented, i just reduced code duplication by replacing a function with an import
- 1.14 is similar to 1.13, but 1.14 chunks store light data separately from the sections themselves (that contain the block data), so when writing to anvil i had to create the bitarrays for each section while saving (which is why BitArray is imported)
- 1.16 is similar to 1.14, but its biomes are implemented differently to 1.14 and 1.15 (biome per 4x4x1 recentangle instead of per 1x1x256 column) so i had to use the newer ChunkSection, as well as it using NoSpan BitArrays instead of normal BitArrays.

note: 1.14-1.16 all needed additional properties added which older versions didnt have, because without them the vanilla minecraft server assumes the "worst" conditions, and essentially just regenerates the chunk, only keeping stuff like biomes, each new property is explained by a comment in the code

will look into reducing code duplication.

**Review by rom1504 — APPROVED** [review]
nice, thanks!

**Comment by rom1504** [comment]
I think we should have more rigorous testing in this module with some actual vanilla worlds to test on, but that's for another issue.
I see you tested manually so that'll be good enough for now :)

**Comment by IdanHo** [comment]
i can look into automatic testing via minecraft-wrap

**Comment by IdanHo** [comment]
will be in a different pull request though

**Comment by rom1504** [comment]
yeah it would be nice, either by regenerating the worlds with minecraft-wrap or just store a few regions directly in the repo for testing (and load/save/load compare)

**Pull request merged**
